(test
 (name test_key)
 (modules test_key)
 (libraries jeditor_terminal alcotest))

(test
 (name test_input)
 (modules test_input)
 (libraries jeditor_terminal alcotest))

(test
 (name test_wcwidth)
 (modules test_wcwidth)
 (libraries jeditor_terminal alcotest))

(test
 (name test_win32_input)
 (modules test_win32_input)
 (libraries jeditor_terminal alcotest)
 (enabled_if (= %{os_type} Win32)))

(test
 (name test_diff_renderer)
 (modules test_diff_renderer)
 (libraries jeditor_terminal alcotest))
